channels:
  - simpleitk
  - conda-forge
dependencies:
  - python==3.10
  - numpy==1.23
  - scikit-image==0.20
  - numba==0.56.4
  - pymaxflow==1.3.0
  - py-opencv==4.6.0
  - pip
  - pip:
    - git+https://github.com/BMRRgroup/fieldmapping-hmrGC